// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQblX-L8CWBNRF46KiqDhqO_BIJljMQC0',
    appId: '1:76631264819:web:72649e7cf27058b11edd46',
    messagingSenderId: '76631264819',
    projectId: 'career-app-ssuhaila',
    authDomain: 'career-app-ssuhaila.firebaseapp.com',
    storageBucket: 'career-app-ssuhaila.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiy3DPR6Dy3GRtMXlNQwxbvPC8A1xxJTE',
    appId: '1:76631264819:android:4c335b36d1f296221edd46',
    messagingSenderId: '76631264819',
    projectId: 'career-app-ssuhaila',
    storageBucket: 'career-app-ssuhaila.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7zOxLM1N0dqJS8y3NquE8B1HonTNRy3Y',
    appId: '1:76631264819:ios:3f4fe0ab474206ba1edd46',
    messagingSenderId: '76631264819',
    projectId: 'career-app-ssuhaila',
    storageBucket: 'career-app-ssuhaila.firebasestorage.app',
    iosBundleId: 'com.example.careerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7zOxLM1N0dqJS8y3NquE8B1HonTNRy3Y',
    appId: '1:76631264819:ios:3f4fe0ab474206ba1edd46',
    messagingSenderId: '76631264819',
    projectId: 'career-app-ssuhaila',
    storageBucket: 'career-app-ssuhaila.firebasestorage.app',
    iosBundleId: 'com.example.careerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQblX-L8CWBNRF46KiqDhqO_BIJljMQC0',
    appId: '1:76631264819:web:5d2da6f5fb5b87f81edd46',
    messagingSenderId: '76631264819',
    projectId: 'career-app-ssuhaila',
    authDomain: 'career-app-ssuhaila.firebaseapp.com',
    storageBucket: 'career-app-ssuhaila.firebasestorage.app',
  );
}
